# Machine utilities are rolling releases; runtime versions live in config/.
brew "git"
brew "gh"
brew "ripgrep"
brew "fd"
brew "jq"
brew "yq"
brew "fzf"
brew "bat"
brew "eza"
brew "zoxide"
brew "starship"
brew "tmux"
brew "direnv"
brew "mise"
brew "uv"
brew "rustup"
brew "cmake"
brew "ninja"
brew "pkgconf"
brew "shellcheck"
brew "shfmt"
brew "git-delta"
brew "just"
brew "container"
# Docker compatibility tools stay installed; Colima starts only on request.
brew "colima"
brew "docker"
brew "docker-compose"
cask "ghostty"
cask "visual-studio-code" unless File.directory?(File.expand_path("~/Applications/Visual Studio Code.app"))

# Everyday development and navigation.
brew "git-lfs"
brew "git-filter-repo"
brew "git-extras"
brew "lazygit"
brew "gitleaks"
brew "lnav"
brew "glow"
brew "yazi"
brew "wget"
brew "socat"
brew "pngpaste"
brew "yamlfmt"
brew "yamllint"
brew "universal-ctags"
brew "zig"

# Interactive shell integration is managed in config/shell.zsh.
brew "zsh-autosuggestions"
brew "zsh-completions"

# Documents, PDF/OCR, images, audio, and video.
brew "imagemagick"
brew "pandoc"
brew "ghostscript"
brew "timg"
brew "ffmpeg"
brew "poppler"
brew "tesseract"

# Matching terminal font for Starship's Nerd Font glyphs.
cask "font-jetbrains-mono-nerd-font"
